[bumpver]
current_version = "2026.01.04"
version_pattern = "YYYY.MM.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[bumpver.file_patterns]
"fireballCollector.py" = [
    "versionid = '{version}'"
]
"README.md" = [
    'Version {version}',
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
#".github/workflows/build_tools.yml" = [
#    'tag_name: {version}',
#]

